Feat: 초기 Spring Security 설정 및 회원 서비스 생성
TEAM-JaChewi/tryit pull request #25
Opened 2022-06-23 15:06 UTC by Kimjunghyunn

## 🚅 PR 한 줄 요약
- Security 설정 및 회원 서비스 생성

## 📋 작업사항
- 초기 Security 설정 
- 회원 서비스 구현
- 회원 서비스 테스트 완료(회원 가입, 중복 회원)

2022-06-23 15:11 UTC, jolly-n commented on src/main/java/shop/tryit/WebSecurityConfig.java
> +public class WebSecurityConfig{
- 스프링이 제공하는 WebSecurityConfigurerAdapter 구글링 한번 해보는 것도 좋을 것 같아요!

2022-06-23 15:14 UTC, jolly-n approved these changes
🐳젛앙용

2022-06-23 15:20 UTC, kureung requested changes

2022-06-23 15:20 UTC, kureung commented on src/main/java/shop/tryit/domain/member/MemberService.java
> +            throw new IllegalStateException("이미 가입된 회원입니다.");
1. findMember 의 변수명과 타입이랑 안 맞는 것 같아요.
findMember는 Member타입  변수로 해야할 것 같은데 boolean 타입이에요.

2. findMember 값 자체로 이미 boolean 값이기 때문에 `!= false` 는 필요없는 것 같아요

저라면 이런식으로 할 것 같아요
``` java
if(repository.existsByEmail(member.getEmail())) {
     throw new IllegalStateException("이미 가입된 회원입니다.");
}
```

2022-06-23 15:20 UTC, kureung commented on src/test/java/shop/tryit/domain/member/MemberServiceTests.java
> +    }
1. MemberFormDto는 뷰에 의존하는 dto인데 서비스 테스트에 있으면 안 될 것 같아요.
2. 테스트 전에 무조건 수행되어야할 메서드가 있다면 `@BeforeEach` 를 사용해보면 어떨까요?

2022-06-24 04:35 UTC, kureung approved these changes

2022-06-24 04:35 UTC, kureung commented on src/test/java/shop/tryit/PasswordEncoderTest.java
> +    }
비밀번호 암호화 테스트는 필요 없는 것 같아요. 왜냐하면 해당 테스트는 본인이 직접 작성한 비즈니스 로직이 아닌 라이브러리에서 지원해주는 암호화 기능이 잘되나 안되나에 대한  테스트입니다. 
그러므로 PasswordEncoder의 encode() 메서드를 테스트하는 것은 라이브러리에 대한 도전입니다.

2022-06-24 04:35 UTC, kureung commented on src/test/java/shop/tryit/domain/member/MemberServiceTests.java
>          assertEquals(member.getEmail(), savedMember.getEmail());
지금 수정할 필요는 없지만 `assertEquals()` 보다는 `assertThat()` 으로 동등성 비교를 해주는 것이 더 좋습니다.
이유 ① 가독성이 더 좋다.
이유 ② AssertJ는 테스트 실패시 실제 값과 예상값을 보여주므로 등 실패 메시지가 더 자세하게 나온다.
참고 자료 : https://jongmin92.github.io/2020/03/31/Java/use-assertthat/

2022-06-24 05:13 UTC, Kimjunghyunn commented on src/test/java/shop/tryit/PasswordEncoderTest.java
> +    }
비밀번호 암호화 bean이 제대로 적용되지 않아 암호화 기능이 적용되었는지 해당 테스트를 통해 확인해 보았습니다.

2022-06-24 05:14 UTC, merged